package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

/**
 * AntecedentesPertCliente generated by hbm2java
 */
public class AntecedentesPertCliente implements java.io.Serializable {

	private Long idAntClie;
	private AntecedentesFamiliares antecedentesFamiliares;
	private Clientes clientes;

	public AntecedentesPertCliente() {
	}

	public AntecedentesPertCliente(AntecedentesFamiliares antecedentesFamiliares, Clientes clientes) {
		this.antecedentesFamiliares = antecedentesFamiliares;
		this.clientes = clientes;
	}

	public Long getIdAntClie() {
		return this.idAntClie;
	}

	public void setIdAntClie(Long idAntClie) {
		this.idAntClie = idAntClie;
	}

	public AntecedentesFamiliares getAntecedentesFamiliares() {
		return this.antecedentesFamiliares;
	}

	public void setAntecedentesFamiliares(AntecedentesFamiliares antecedentesFamiliares) {
		this.antecedentesFamiliares = antecedentesFamiliares;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

}
