package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Blog generated by hbm2java
 */
public class Blog implements java.io.Serializable {

	private Long idBlog;
	private Categoria categoria;
	private String autorBlog;
	private String tituloBlog;
	private Date fechaEntrada;
	private String nombreArchivo;
	private Set nutriComentarioses = new HashSet(0);

	public Blog() {
	}
	
	public Blog(Long idBlog, String tituloBlog) {
		this.idBlog = idBlog;
		this.tituloBlog = tituloBlog;
	}
	
	public Blog(Long idBlog, String autorBlog, String tituloBlog) {
		this.idBlog = idBlog;
		this.autorBlog = autorBlog;
		this.tituloBlog = tituloBlog;
	}

	public Blog(Categoria categoria, String autorBlog, String tituloBlog, Date fechaEntrada, String nombreArchivo) {
		this.categoria = categoria;
		this.autorBlog = autorBlog;
		this.tituloBlog = tituloBlog;
		this.fechaEntrada = fechaEntrada;
		this.nombreArchivo = nombreArchivo;
	}

	public Blog(Categoria categoria, String autorBlog, String tituloBlog, Date fechaEntrada, String nombreArchivo,
			Set nutriComentarioses) {
		this.categoria = categoria;
		this.autorBlog = autorBlog;
		this.tituloBlog = tituloBlog;
		this.fechaEntrada = fechaEntrada;
		this.nombreArchivo = nombreArchivo;
		this.nutriComentarioses = nutriComentarioses;
	}

	public Long getIdBlog() {
		return this.idBlog;
	}

	public void setIdBlog(Long idBlog) {
		this.idBlog = idBlog;
	}

	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public String getAutorBlog() {
		return this.autorBlog;
	}

	public void setAutorBlog(String autorBlog) {
		this.autorBlog = autorBlog;
	}

	public String getTituloBlog() {
		return this.tituloBlog;
	}

	public void setTituloBlog(String tituloBlog) {
		this.tituloBlog = tituloBlog;
	}

	public Date getFechaEntrada() {
		return this.fechaEntrada;
	}

	public void setFechaEntrada(Date fechaEntrada) {
		this.fechaEntrada = fechaEntrada;
	}

	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	public Set getNutriComentarioses() {
		return this.nutriComentarioses;
	}

	public void setNutriComentarioses(Set nutriComentarioses) {
		this.nutriComentarioses = nutriComentarioses;
	}

}
