package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private String categoria;
	private Set blogs = new HashSet(0);

	public Categoria() {
	}

	public Categoria(String categoria) {
		this.categoria = categoria;
	}

	public Categoria(String categoria, Set blogs) {
		this.categoria = categoria;
		this.blogs = blogs;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public Set getBlogs() {
		return this.blogs;
	}

	public void setBlogs(Set blogs) {
		this.blogs = blogs;
	}

}
