package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.sql.Time;
import java.util.Date;

/**
 * Citas generated by hbm2java
 */
public class Citas implements java.io.Serializable {

	private Long idCita;
	private Clientes clientes;
	private Date fechaCita;
	private Time horaCita;
	private Boolean activa;
	private Boolean confirmar;
	private Boolean asistencia;
	private Boolean online;
	private String presencial;
	private String direccion;
	private String motivo;
	private String observaciones;

	public Citas() {
	}

	public Citas(Date fechaCita, Time horaCita, boolean confirmar) {
		this.fechaCita = fechaCita;
		this.horaCita = horaCita;
		this.confirmar = confirmar;
	}

	public Citas(Long idCita, Clientes clientes, Date fechaCita, Time horaCita, Boolean activa, boolean confirmar,
			Boolean asistencia,Boolean online, String presencial, String direccion,String motivo,String observaciones) {
		this.idCita = idCita;
		this.clientes = clientes;
		this.fechaCita = fechaCita;
		this.horaCita = horaCita;
		this.activa = activa;
		this.confirmar = confirmar;
		this.asistencia = asistencia;
		this.online = online;
		this.presencial = presencial;
		this.direccion = direccion;
		this.motivo = motivo;
		this.observaciones = observaciones;
	}

	public Long getIdCita() {
		return this.idCita;
	}

	public void setIdCita(Long idCita) {
		this.idCita = idCita;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Date getFechaCita() {
		return this.fechaCita;
	}

	public void setFechaCita(Date fechaCita) {
		this.fechaCita = fechaCita;
	}

	public Date getHoraCita() {
		return this.horaCita;
	}

	public void setHoraCita(Time horaCita) {
		this.horaCita = horaCita;
	}

	public Boolean getActiva() {
		return this.activa;
	}

	public void setActiva(Boolean activa) {
		this.activa = activa;
	}

	public Boolean getConfirmar() {
		return this.confirmar;
	}

	public void setConfirmar(Boolean confirmar) {
		this.confirmar = confirmar;
	}

	public Boolean getAsistencia() {
		return this.asistencia;
	}

	public void setAsistencia(Boolean asistencia) {
		this.asistencia = asistencia;
	}

	public Boolean getOnline() {
		return online;
	}

	public void setOnline(Boolean online) {
		this.online = online;
	}

	public String getPresencial() {
		return presencial;
	}

	public void setPresencial(String presencial) {
		this.presencial = presencial;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getMotivo() {
		return motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}
	
	
}
