package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements Serializable {

	private String emailId;
	private String dniNif;
	private String nombre;
	private String apellidos;
	private Date fechaNacimiento;
	private int telefono;
	private String trabajo;
	private Float pesoLimite;
	private Float objetivoPeso;
	private Integer altura;
	private Integer actividadFisica;
	private String objetivo;
	private Boolean mastica;
	private Boolean sueño;
	private Integer estres;
	private Set antecedentesPertClientes = new HashSet(0);
	private Set citases = new HashSet(0);
	private Set dietasClienteses = new HashSet(0);
	private Mediciones pliegues;
	private Set suplementosClientes = new HashSet(0);
	private Set usuarioses = new HashSet(0);

	public Clientes() {
		
	}

	public Clientes(String emailId, String nombre, String apellidos, int telefono) {
		this.emailId = emailId;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
	}
	public Clientes(String emailId, String nombre, String apellidos,String dniNif, Date fechaNacimiento, int telefono) {
		this.emailId = emailId;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.telefono = telefono;
		this.fechaNacimiento = fechaNacimiento;
		this.dniNif = dniNif;
	}

	public Clientes(String emailId, String dniNif, String nombre, String apellidos, Date fechaNacimiento, int telefono,
			String trabajo, Float pesoLimite, Float objetivoPeso, Integer altura, Integer actividadFisica,
			String objetivo, Boolean mastica, Boolean sueño, Integer estres, Set antecedentesPertClientes, Set citases,
			Set dietasClienteses, Mediciones pliegues, Set suplementosClientes, Set usuarioses) {
		this.emailId = emailId;
		this.dniNif = dniNif;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaNacimiento = fechaNacimiento;
		this.telefono = telefono;
		this.trabajo = trabajo;
		this.pesoLimite = pesoLimite;
		this.objetivoPeso = objetivoPeso;
		this.altura = altura;
		this.actividadFisica = actividadFisica;
		this.objetivo = objetivo;
		this.mastica = mastica;
		this.sueño = sueño;
		this.estres = estres;
		this.antecedentesPertClientes = antecedentesPertClientes;
		this.citases = citases;
		this.dietasClienteses = dietasClienteses;
		this.pliegues = pliegues;
		this.suplementosClientes = suplementosClientes;
		this.usuarioses = usuarioses;
	}

	public boolean empiezaPor(String inicio) {
        if(inicio.isEmpty() || inicio.length()>nombre.length())
            return false;
        for(int i=0; i<inicio.length(); ++i)
            if( inicio.charAt(i) != nombre.charAt(i) )
                return false;
        return true;
    }
	
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public String getDniNif() {
		return this.dniNif;
	}

	public void setDniNif(String dniNif) {
		this.dniNif = dniNif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getTrabajo() {
		return this.trabajo;
	}

	public void setTrabajo(String trabajo) {
		this.trabajo = trabajo;
	}

	public Float getPesoLimite() {
		return this.pesoLimite;
	}

	public void setPesoLimite(Float pesoLimite) {
		this.pesoLimite = pesoLimite;
	}

	public Float getObjetivoPeso() {
		return this.objetivoPeso;
	}

	public void setObjetivoPeso(Float objetivoPeso) {
		this.objetivoPeso = objetivoPeso;
	}

	public Integer getAltura() {
		return this.altura;
	}

	public void setAltura(Integer altura) {
		this.altura = altura;
	}

	public Integer getActividadFisica() {
		return this.actividadFisica;
	}

	public void setActividadFisica(Integer actividadFisica) {
		this.actividadFisica = actividadFisica;
	}

	public String getObjetivo() {
		return this.objetivo;
	}

	public void setObjetivo(String objetivo) {
		this.objetivo = objetivo;
	}

	public Boolean getMastica() {
		return this.mastica;
	}

	public void setMastica(Boolean mastica) {
		this.mastica = mastica;
	}

	public Boolean getSueño() {
		return this.sueño;
	}

	public void setSueño(Boolean sueño) {
		this.sueño = sueño;
	}

	public Integer getEstres() {
		return this.estres;
	}

	public void setEstres(Integer estres) {
		this.estres = estres;
	}

	public Set getAntecedentesPertClientes() {
		return this.antecedentesPertClientes;
	}

	public void setAntecedentesPertClientes(Set antecedentesPertClientes) {
		this.antecedentesPertClientes = antecedentesPertClientes;
	}

	public Set getCitases() {
		return this.citases;
	}

	public void setCitases(Set citases) {
		this.citases = citases;
	}

	public Set getDietasClienteses() {
		return this.dietasClienteses;
	}

	public void setDietasClienteses(Set dietasClienteses) {
		this.dietasClienteses = dietasClienteses;
	}

	public Mediciones getPliegues() {
		return this.pliegues;
	}

	public void setPliegues(Mediciones pliegues) {
		this.pliegues = pliegues;
	}

	public Set getSuplementosClientes() {
		return this.suplementosClientes;
	}

	public void setSuplementosClientes(Set suplementosClientes) {
		this.suplementosClientes = suplementosClientes;
	}

	public Set getUsuarioses() {
		return this.usuarioses;
	}

	public void setUsuarioses(Set usuarioses) {
		this.usuarioses = usuarioses;
	}
	@Override
    public String toString() {
        return "Nombre completo: "+apellidos+", "+nombre+
               "\nDni: "+dniNif+
               "\nCorreo: "+emailId;
    }

}
