package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

/**
 * DietasClientes generated by hbm2java
 */
public class DietasClientes implements java.io.Serializable {

	private Long idDietaCliente;
	private Clientes clientes;
	private Dietas dietas;

	public DietasClientes() {
	}

	public DietasClientes(Clientes clientes, Dietas dietas) {
		this.clientes = clientes;
		this.dietas = dietas;
	}

	public Long getIdDietaCliente() {
		return this.idDietaCliente;
	}

	public void setIdDietaCliente(Long idDietaCliente) {
		this.idDietaCliente = idDietaCliente;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Dietas getDietas() {
		return this.dietas;
	}

	public void setDietas(Dietas dietas) {
		this.dietas = dietas;
	}

}
