package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Dietas generated by hbm2java
 */
public class Dietas implements java.io.Serializable {

	private Integer idDietas;
	private String nombreDieta;
	private Set dietasClienteses = new HashSet(0);

	public Dietas() {
	}

	public Dietas(String nombreDieta) {
		this.nombreDieta = nombreDieta;
	}

	public Dietas(String nombreDieta, Set dietasClienteses) {
		this.nombreDieta = nombreDieta;
		this.dietasClienteses = dietasClienteses;
	}

	public Integer getIdDietas() {
		return this.idDietas;
	}

	public void setIdDietas(Integer idDietas) {
		this.idDietas = idDietas;
	}

	public String getNombreDieta() {
		return this.nombreDieta;
	}

	public void setNombreDieta(String nombreDieta) {
		this.nombreDieta = nombreDieta;
	}

	public Set getDietasClienteses() {
		return this.dietasClienteses;
	}

	public void setDietasClienteses(Set dietasClienteses) {
		this.dietasClienteses = dietasClienteses;
	}

}
