package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Pliegues generated by hbm2java
 */
public class Mediciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5885557978547366283L;
	private String idCliente;
	private Clientes clientes;
	private float triceps;
	private float espalda;
	private float biceps;
	private float pecho;
	private float axsila;
	private float crestaHiliaca;
	private float supraEspinal;
	private float abdomen;
	private float cuadricepsDelantero;
	private float cuadricepsTrasero;
	private float p_cintura;
	private float p_cadera;
	private float p_brazo_relajado;
	private float p_brazo_contraido;
	private float p_muslo;
	private float p_pierna;
	private float peso;
	private Date fechaMedicion;

	public Mediciones() {
	}

	public Mediciones(Clientes clientes, Date fechaMedicion) {
		this.clientes = clientes;
		this.fechaMedicion = fechaMedicion;
	}
	

	public Mediciones(String idCliente, Clientes clientes, float triceps, float espalda, float biceps, float pecho,
			float axsila, float crestaHiliaca, float supraEspinal, float abdomen, float cuadricepsDelantero,
			float cuadricepsTrasero, float p_cintura, float p_cadera, float p_brazo_relajado, float p_brazo_contraido,
			float p_muslo, float p_pierna, float peso, Date fechaMedicion) {
		super();
		this.idCliente = idCliente;
		this.clientes = clientes;
		this.triceps = triceps;
		this.espalda = espalda;
		this.biceps = biceps;
		this.pecho = pecho;
		this.axsila = axsila;
		this.crestaHiliaca = crestaHiliaca;
		this.supraEspinal = supraEspinal;
		this.abdomen = abdomen;
		this.cuadricepsDelantero = cuadricepsDelantero;
		this.cuadricepsTrasero = cuadricepsTrasero;
		this.p_cintura = p_cintura;
		this.p_cadera = p_cadera;
		this.p_brazo_relajado = p_brazo_relajado;
		this.p_brazo_contraido = p_brazo_contraido;
		this.p_muslo = p_muslo;
		this.p_pierna = p_pierna;
		this.peso = peso;
		this.fechaMedicion = fechaMedicion;
	}
	public Mediciones(String idCliente, float triceps, float espalda, float biceps, float pecho,
			float axsila, float crestaHiliaca, float supraEspinal, float abdomen, float cuadricepsDelantero,
			float cuadricepsTrasero, float p_cintura, float p_cadera, float p_brazo_relajado, float p_brazo_contraido,
			float p_muslo, float p_pierna, float peso, Date fechaMedicion) {
		super();
		this.idCliente = idCliente;
		this.triceps = triceps;
		this.espalda = espalda;
		this.biceps = biceps;
		this.pecho = pecho;
		this.axsila = axsila;
		this.crestaHiliaca = crestaHiliaca;
		this.supraEspinal = supraEspinal;
		this.abdomen = abdomen;
		this.cuadricepsDelantero = cuadricepsDelantero;
		this.cuadricepsTrasero = cuadricepsTrasero;
		this.p_cintura = p_cintura;
		this.p_cadera = p_cadera;
		this.p_brazo_relajado = p_brazo_relajado;
		this.p_brazo_contraido = p_brazo_contraido;
		this.p_muslo = p_muslo;
		this.p_pierna = p_pierna;
		this.peso = peso;
		this.fechaMedicion = fechaMedicion;
	}

	public String getIdCliente() {
		return idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public Clientes getClientes() {
		return clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public float getTriceps() {
		return triceps;
	}

	public void setTriceps(float triceps) {
		this.triceps = triceps;
	}

	public float getEspalda() {
		return espalda;
	}

	public void setEspalda(float espalda) {
		this.espalda = espalda;
	}

	public float getBiceps() {
		return biceps;
	}

	public void setBiceps(float biceps) {
		this.biceps = biceps;
	}

	public float getPecho() {
		return pecho;
	}

	public void setPecho(float pecho) {
		this.pecho = pecho;
	}

	public float getAxsila() {
		return axsila;
	}

	public void setAxsila(float axsila) {
		this.axsila = axsila;
	}

	public float getCrestaHiliaca() {
		return crestaHiliaca;
	}

	public void setCrestaHiliaca(float crestaHiliaca) {
		this.crestaHiliaca = crestaHiliaca;
	}

	public float getSupraEspinal() {
		return supraEspinal;
	}

	public void setSupraEspinal(float supraEspinal) {
		this.supraEspinal = supraEspinal;
	}

	public float getAbdomen() {
		return abdomen;
	}

	public void setAbdomen(float abdomen) {
		this.abdomen = abdomen;
	}

	public float getCuadricepsDelantero() {
		return cuadricepsDelantero;
	}

	public void setCuadricepsDelantero(float cuadricepsDelantero) {
		this.cuadricepsDelantero = cuadricepsDelantero;
	}

	public float getCuadricepsTrasero() {
		return cuadricepsTrasero;
	}

	public void setCuadricepsTrasero(float cuadricepsTrasero) {
		this.cuadricepsTrasero = cuadricepsTrasero;
	}

	public float getP_cintura() {
		return p_cintura;
	}

	public void setP_cintura(float p_cintura) {
		this.p_cintura = p_cintura;
	}

	public float getP_cadera() {
		return p_cadera;
	}

	public void setP_cadera(float p_cadera) {
		this.p_cadera = p_cadera;
	}

	public float getP_brazo_relajado() {
		return p_brazo_relajado;
	}

	public void setP_brazo_relajado(float p_brazo_relajado) {
		this.p_brazo_relajado = p_brazo_relajado;
	}

	public float getP_brazo_contraido() {
		return p_brazo_contraido;
	}

	public void setP_brazo_contraido(float p_brazo_contraido) {
		this.p_brazo_contraido = p_brazo_contraido;
	}

	public float getP_muslo() {
		return p_muslo;
	}

	public void setP_muslo(float p_muslo) {
		this.p_muslo = p_muslo;
	}

	public float getP_pierna() {
		return p_pierna;
	}

	public void setP_pierna(float p_pierna) {
		this.p_pierna = p_pierna;
	}

	public float getPeso() {
		return peso;
	}

	public void setPeso(float peso) {
		this.peso = peso;
	}

	public Date getFechaMedicion() {
		return fechaMedicion;
	}

	public void setFechaMedicion(Date fechaMedicion) {
		this.fechaMedicion = fechaMedicion;
	}

	
}
