package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * NutriLinks generated by hbm2java
 */
public class NutriLinks implements java.io.Serializable {

	private Long linkId;
	private String linkUrl;
	private String linkName;
	private String linkImage;
	private String linkTarget;
	private String linkDescription;
	private String linkVisible;
	private long linkOwner;
	private int linkRating;
	private Date linkUpdated;
	private String linkRel;
	private String linkNotes;
	private String linkRss;

	public NutriLinks() {
	}

	public NutriLinks(String linkUrl, String linkName, String linkImage, String linkTarget, String linkDescription,
			String linkVisible, long linkOwner, int linkRating, Date linkUpdated, String linkRel, String linkNotes,
			String linkRss) {
		this.linkUrl = linkUrl;
		this.linkName = linkName;
		this.linkImage = linkImage;
		this.linkTarget = linkTarget;
		this.linkDescription = linkDescription;
		this.linkVisible = linkVisible;
		this.linkOwner = linkOwner;
		this.linkRating = linkRating;
		this.linkUpdated = linkUpdated;
		this.linkRel = linkRel;
		this.linkNotes = linkNotes;
		this.linkRss = linkRss;
	}

	public Long getLinkId() {
		return this.linkId;
	}

	public void setLinkId(Long linkId) {
		this.linkId = linkId;
	}

	public String getLinkUrl() {
		return this.linkUrl;
	}

	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl;
	}

	public String getLinkName() {
		return this.linkName;
	}

	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}

	public String getLinkImage() {
		return this.linkImage;
	}

	public void setLinkImage(String linkImage) {
		this.linkImage = linkImage;
	}

	public String getLinkTarget() {
		return this.linkTarget;
	}

	public void setLinkTarget(String linkTarget) {
		this.linkTarget = linkTarget;
	}

	public String getLinkDescription() {
		return this.linkDescription;
	}

	public void setLinkDescription(String linkDescription) {
		this.linkDescription = linkDescription;
	}

	public String getLinkVisible() {
		return this.linkVisible;
	}

	public void setLinkVisible(String linkVisible) {
		this.linkVisible = linkVisible;
	}

	public long getLinkOwner() {
		return this.linkOwner;
	}

	public void setLinkOwner(long linkOwner) {
		this.linkOwner = linkOwner;
	}

	public int getLinkRating() {
		return this.linkRating;
	}

	public void setLinkRating(int linkRating) {
		this.linkRating = linkRating;
	}

	public Date getLinkUpdated() {
		return this.linkUpdated;
	}

	public void setLinkUpdated(Date linkUpdated) {
		this.linkUpdated = linkUpdated;
	}

	public String getLinkRel() {
		return this.linkRel;
	}

	public void setLinkRel(String linkRel) {
		this.linkRel = linkRel;
	}

	public String getLinkNotes() {
		return this.linkNotes;
	}

	public void setLinkNotes(String linkNotes) {
		this.linkNotes = linkNotes;
	}

	public String getLinkRss() {
		return this.linkRss;
	}

	public void setLinkRss(String linkRss) {
		this.linkRss = linkRss;
	}

}
