package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * ReplyComents generated by hbm2java
 */
public class ReplyComents implements java.io.Serializable {

	private Long idReply;
	private NutriComentarios nutriComentarios;
	private String comentarioRespondidoTexto;
	private String ipAutorRespuesta;
	private String emailAutorRespuesta;
	private String nombreAutor;
	private String fotoAutorRespuesta;
	private Boolean aprovadoRespuesta;
	private Date fechaRespuesta;

	public ReplyComents() {
	}

	public ReplyComents(NutriComentarios nutriComentarios, String comentarioRespondidoTexto, String emailAutorRespuesta,
			String nombreAutor, Date fechaRespuesta) {
		this.nutriComentarios = nutriComentarios;
		this.comentarioRespondidoTexto = comentarioRespondidoTexto;
		this.emailAutorRespuesta = emailAutorRespuesta;
		this.nombreAutor = nombreAutor;
		this.fechaRespuesta = fechaRespuesta;
	}

	public ReplyComents(NutriComentarios nutriComentarios, String comentarioRespondidoTexto, String ipAutorRespuesta,
			String emailAutorRespuesta, String nombreAutor, String fotoAutorRespuesta, Boolean aprovadoRespuesta,
			Date fechaRespuesta) {
		this.nutriComentarios = nutriComentarios;
		this.comentarioRespondidoTexto = comentarioRespondidoTexto;
		this.ipAutorRespuesta = ipAutorRespuesta;
		this.emailAutorRespuesta = emailAutorRespuesta;
		this.nombreAutor = nombreAutor;
		this.fotoAutorRespuesta = fotoAutorRespuesta;
		this.aprovadoRespuesta = aprovadoRespuesta;
		this.fechaRespuesta = fechaRespuesta;
	}

	public Long getIdReply() {
		return this.idReply;
	}

	public void setIdReply(Long idReply) {
		this.idReply = idReply;
	}

	public NutriComentarios getNutriComentarios() {
		return this.nutriComentarios;
	}

	public void setNutriComentarios(NutriComentarios nutriComentarios) {
		this.nutriComentarios = nutriComentarios;
	}

	public String getComentarioRespondidoTexto() {
		return this.comentarioRespondidoTexto;
	}

	public void setComentarioRespondidoTexto(String comentarioRespondidoTexto) {
		this.comentarioRespondidoTexto = comentarioRespondidoTexto;
	}

	public String getIpAutorRespuesta() {
		return this.ipAutorRespuesta;
	}

	public void setIpAutorRespuesta(String ipAutorRespuesta) {
		this.ipAutorRespuesta = ipAutorRespuesta;
	}

	public String getEmailAutorRespuesta() {
		return this.emailAutorRespuesta;
	}

	public void setEmailAutorRespuesta(String emailAutorRespuesta) {
		this.emailAutorRespuesta = emailAutorRespuesta;
	}

	public String getNombreAutor() {
		return this.nombreAutor;
	}

	public void setNombreAutor(String nombreAutor) {
		this.nombreAutor = nombreAutor;
	}

	public String getFotoAutorRespuesta() {
		return this.fotoAutorRespuesta;
	}

	public void setFotoAutorRespuesta(String fotoAutorRespuesta) {
		this.fotoAutorRespuesta = fotoAutorRespuesta;
	}

	public Boolean getAprovadoRespuesta() {
		return this.aprovadoRespuesta;
	}

	public void setAprovadoRespuesta(Boolean aprovadoRespuesta) {
		this.aprovadoRespuesta = aprovadoRespuesta;
	}

	public Date getFechaRespuesta() {
		return this.fechaRespuesta;
	}

	public void setFechaRespuesta(Date fechaRespuesta) {
		this.fechaRespuesta = fechaRespuesta;
	}

}
