package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Suplementos generated by hbm2java
 */
public class Suplementos implements java.io.Serializable {

	private Integer idSuplemento;
	private String nombreSup;
	private Set suplementosClientes = new HashSet(0);

	public Suplementos() {
	}

	public Suplementos(String nombreSup) {
		this.nombreSup = nombreSup;
	}

	public Suplementos(String nombreSup, Set suplementosClientes) {
		this.nombreSup = nombreSup;
		this.suplementosClientes = suplementosClientes;
	}

	public Integer getIdSuplemento() {
		return this.idSuplemento;
	}

	public void setIdSuplemento(Integer idSuplemento) {
		this.idSuplemento = idSuplemento;
	}

	public String getNombreSup() {
		return this.nombreSup;
	}

	public void setNombreSup(String nombreSup) {
		this.nombreSup = nombreSup;
	}

	public Set getSuplementosClientes() {
		return this.suplementosClientes;
	}

	public void setSuplementosClientes(Set suplementosClientes) {
		this.suplementosClientes = suplementosClientes;
	}

}
