package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

/**
 * SuplementosCliente generated by hbm2java
 */
public class SuplementosCliente implements java.io.Serializable {

	private Long idSupCliente;
	private Clientes clientes;
	private Suplementos suplementos;

	public SuplementosCliente() {
	}

	public SuplementosCliente(Clientes clientes, Suplementos suplementos) {
		this.clientes = clientes;
		this.suplementos = suplementos;
	}

	public Long getIdSupCliente() {
		return this.idSupCliente;
	}

	public void setIdSupCliente(Long idSupCliente) {
		this.idSupCliente = idSupCliente;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Suplementos getSuplementos() {
		return this.suplementos;
	}

	public void setSuplementos(Suplementos suplementos) {
		this.suplementos = suplementos;
	}

}
