package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Suscripciones generated by hbm2java
 */
public class Suscripciones implements java.io.Serializable {

	private String emailSuscrito;
	private String ipSuscrito;
	private Date fechaSuscripcion;

	public Suscripciones() {
	}

	public Suscripciones(String emailSuscrito, Date fechaSuscripcion) {
		this.emailSuscrito = emailSuscrito;
		this.fechaSuscripcion = fechaSuscripcion;
	}

	public Suscripciones(String emailSuscrito, String ipSuscrito, Date fechaSuscripcion) {
		this.emailSuscrito = emailSuscrito;
		this.ipSuscrito = ipSuscrito;
		this.fechaSuscripcion = fechaSuscripcion;
	}

	public String getEmailSuscrito() {
		return this.emailSuscrito;
	}

	public void setEmailSuscrito(String emailSuscrito) {
		this.emailSuscrito = emailSuscrito;
	}

	public String getIpSuscrito() {
		return this.ipSuscrito;
	}

	public void setIpSuscrito(String ipSuscrito) {
		this.ipSuscrito = ipSuscrito;
	}

	public Date getFechaSuscripcion() {
		return this.fechaSuscripcion;
	}

	public void setFechaSuscripcion(Date fechaSuscripcion) {
		this.fechaSuscripcion = fechaSuscripcion;
	}

}
