package generadas;
// default package
// Generated 9 mar. 2022 19:42:08 by Hibernate Tools 5.6.3.Final

import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer idUser;
	private Clientes clientes;
	private String userLogin;
	private String userPass;
	private Date userRegistered;
	private Integer userStatus;
	private String userUrl;

	public Usuarios() {
	}

	public Usuarios(Clientes clientes, String userLogin, String userPass, Date userRegistered, Integer userStatus,
			String userUrl) {
		this.clientes = clientes;
		this.userLogin = userLogin;
		this.userPass = userPass;
		this.userRegistered = userRegistered;
		this.userStatus = userStatus;
		this.userUrl = userUrl;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	public Date getUserRegistered() {
		return this.userRegistered;
	}

	public void setUserRegistered(Date userRegistered) {
		this.userRegistered = userRegistered;
	}

	public Integer getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(Integer userStatus) {
		this.userStatus = userStatus;
	}

	public String getUserUrl() {
		return this.userUrl;
	}

	public void setUserUrl(String userUrl) {
		this.userUrl = userUrl;
	}

}
